### ISSUE TITLE
Auto scrolling when text overflows

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#1]
**Actual behaviour**
When messages overflow the `div` that contains messages then scroll is added, but it does not scrolls automatically.
**Expected behaviour**
Scroll automatically when messages overflow.
![textoverflow](https://user-images.githubusercontent.com/20766601/30657825-6d3915e8-9e56-11e7-9df3-6237b8c91977.png)

**Comment by zamhaq** [comment]
@mariobehling Do you have to add me as an assignee ? If yes, then please assign this to me. I will be working on this issue.
Thanks.

**Comment by AliAyub007** [comment]
@zamhaq Does SUSI Chrome extension get the responses from SUSI API? I just saw that currently, it is sending the hardcoded message.

**Comment by zamhaq** [comment]
@AliAyub007 No. It is not done yet. I was concentrating on the front end for now. The API is yet to be integrated.

**Comment by gabru-md** [comment]
I would like to try to solve it!
