### ISSUE TITLE
Add Travis and Codacy checks

### ISSUE THREAD

**Issue by hpdang** [fossasia/susi_chromebot#10]
Please add Travis and Codacy.

**Comment by gabru-md** [comment]
Claiming!

**Comment by tstreamDOTh** [comment]
@gabru-md  Please add Travis and Codacy as soon as possible. The code quality is not being monitored. Please read through https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/ 😊

**Comment by gabru-md** [comment]
Working on it!
WIll do it asap

**Comment by gabru-md** [comment]
@tstreamDOTh I am having trouble adding tests for travis.
I might need some help

**Comment by tstreamDOTh** [comment]
@gabru-md any updates?

**Comment by gabru-md** [comment]
@tstreamDOTh I am working on it!
If i am not able to send a PR by tomorrow then you may work on it.
Sorry for inconvenience.

**Comment by zamhaq** [comment]
@gabru-md what's the status on this issue ?

**Comment by ms10398** [comment]
@zamhaq I will be working on integrating Travis collabrating with @gabru-md

**Comment by ms10398** [comment]
@zamhaq Codacy can only be implemented by you as you are the one with the write access to the repository so you should try to implement it and close this issue!! Cheers

**Comment by zamhaq** [comment]
Oh okay @ms10398. Will do that.
