### ISSUE TITLE
alerting the user if the mic is not allowed

### ISSUE THREAD

**Issue by rupav** [fossasia/susi_chromebot#100]
**Actual Behaviour **
![2017-10-01 3](https://user-images.githubusercontent.com/20624380/31054521-d178c28c-a6d1-11e7-94da-d92d96959313.png)
**Expected Behaviour**
An alert message for user to change the setting on the top.
**Would you like to do it?**
Yes

**Comment by rupav** [comment]
@zamhaq as suggested, I will do it ASAP :)

**Comment by zamhaq** [comment]
@rupav Please mention the `actual behavior` and `expected behavior`. Thanks.

**Comment by rupav** [comment]
@zamhaq  @gabru-md  help needed in this:
So basically when 'settings' button got clicked line, 280 gets executed 
![2017-10-02](https://user-images.githubusercontent.com/20624380/31066034-893fce70-a767-11e7-8f37-d621cafe0dc2.png)

Now what I want is to set a variable say 'settings_clicked' = true and use it in 'if else' like statements for accessing toggleStartStop() in between 274-276 lines. 
But this is not working as everytime 'setting' button gets clicked, a new tab is opened for 'options.html' and thus my variable 'settings_clicked' gets lost since  that popup gets closed and thus script.js too. 
Can you guys please help me out in this.
Thanks.

**Comment by gabru-md** [comment]
A better way would be to update the readme for the same, directing the user on how to setup this extension before using it.
@rupav you can leave this issue and update the readme for the same. And if you can then look for anything else that can be mentioned in the readme.
Thanks

**Comment by zamhaq** [comment]
@rupav what you could do is check if mic is allowed using chrome apis(search if this can be done) .  If its not then alert user about no mic allowed and how he can enable it. You can try or else leave it and I'll work on this. 
For now, there is no way you can keep that variable state, I am working persistent storage.

**Comment by gabru-md** [comment]
@zamhaq this issue has been taken care of and appropriate changes have been made to the readme.
Please see the pull request that @rupav has made.
Thanks

**Comment by zamhaq** [comment]
@gabru-md while documentation was needed about setting up the microphone, that does not solve the issue when the user tries to access mic without allowing it. I think the issue should be open.

**Comment by rupav** [comment]
@zamhaq I will look into this then as per your suggestion. Will update you within 3 days.

**Comment by zamhaq** [comment]
@rupav whats the status on this?

**Comment by rupav** [comment]
Hi @zamhaq , I wasn't able to look much into it, and also busy in coming couple of days. So please take up the issue :) . Apologies for not sharing the progress.

**Comment by rupav** [comment]
@zamhaq are you working on this? Can i continue if you are not ? :)

**Comment by zamhaq** [comment]
@rupav yeah, you can work on this.

**Comment by zamhaq** [comment]
@rupav what's the status?

**Comment by rupav** [comment]
@zamhaq  will update you by tomorrow night positively.

**Comment by zamhaq** [comment]
@rupav please update.

**Comment by rupav** [comment]
@zamhaq  At the moment, I can access mic without even allowing the settings option. Please check if its true on your end too. I removed the extension and loaded it again, still seeing the same behaviour.

**Comment by zamhaq** [comment]
@rupav No problem. I will fix this.

**Comment by ms10398** [comment]
Can I work on it as I have figured out a way to do it and implemented it.

**Comment by zamhaq** [comment]
@ms10398 sure
