### ISSUE TITLE
UI Enchancement(Scrollbar)

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#102]
Its a UI enchancement now the scrollbar is really simple I would like to enchance its look and make it attractive.

@zamhaq @gabru-md Whats your opinion?

**Comment by zamhaq** [comment]
sure

**Comment by ms10398** [comment]
Thanks will make a relevant PR soon
Till then can you review my PR https://github.com/fossasia/susi_chromebot/pull/101

**Comment by zamhaq** [comment]
I did approve it yesterday. @ms10398 seems your PR closed. Anyways, will merge once others approve. :+1:

**Comment by ms10398** [comment]
Yes I resetted my fork with upstream and that PR got closed so I made the changes again and sent a PR.
Thanks yes merge it after others approve it.

**Comment by mariobehling** [comment]
The main goal of the clients is to enable a smooth communication of SUSI.AI with the user. The goal is not to push certain UI elements to the user. While another scroll bar could look cool for certain use cases, here it is important to keep it simple and neat and avoid too shiny colors that distract the user from the actual content. Therefore closing it.
