### ISSUE TITLE
SUSI should not always SPEAK

### ISSUE THREAD

**Issue by gabru-md** [fossasia/susi_chromebot#110]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Currently the bot speaks for every response.

**Expected behavior:**

The user must have an option like to toggle TTS, There must be a button to mute/unmute SUSI.

**Steps to reproduce:**

**Would you like to work on the issue?**
`
**YES** I will work on this.

**Comment by ms10398** [comment]
@gabru-md I would like to ask is the TTS working because its not working on my PC.

**Comment by zamhaq** [comment]
@gabru-md yes it's working for me.

**Comment by ms10398** [comment]
Is there any setting we need to do for it

**Comment by zamhaq** [comment]
@ms10398 the initial setting to allow microphone, through settings.

**Comment by gabru-md** [comment]
@ms10398 It works fine for me as well. You need to allow the bot to access the microphone

**Comment by ms10398** [comment]
I have allowed I will check it again.
