### ISSUE TITLE
Adding the login portal to chromebot

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#111]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Only the login button is present.

**Expected behavior:**
The need to add a login form

**System information:**

```
Your operating system
MAC OS

**Would you like to work on the issue?**

Yes i would like to work on this issue
```
![31082760-6420afba-a7ad-11e7-99b7-292b45bf5bde](https://user-images.githubusercontent.com/29942790/31235239-9bfe3e30-aa0e-11e7-8890-b9b7ab150e5d.png)

**Comment by gabru-md** [comment]
Why this ?

**Comment by stealthanthrax** [comment]
@gabru-md,because there is a login portal on the main chat bot: so,i was thinking whether it is required or not

**Comment by gabru-md** [comment]
okay! @zamhaq @ms10398 Please see

**Comment by zamhaq** [comment]
@stealthanthrax are going implement only the link or the complete functionality? Maintaining sessions and all?

**Comment by gabru-md** [comment]
@stealthanthrax I guess that Only the link would be sufficient as this is just a chrome extension and there is no need to add this stuff to it.
Let's keep it to what it should be and not wander from the ultimate path of making it a chrome-chat-bot for susi.

**Comment by ms10398** [comment]
@gabru-md Agreed

**Comment by zamhaq** [comment]
@stealthanthrax @gabru-md do you think `login` link is even useful? Since it would not actually log in the user from the extension and there would be no `sessions`. I think we should drop the link and option to `login`. Otherwise, it would be just like a shortcut for logging in.

**Comment by ms10398** [comment]
Yes we should drop the link as it is of no use in the extension.

**Comment by stealthanthrax** [comment]
@zamhaq @ms10398  ,if we can find a way to add a remote login/logout to the main susi-server : so,will that be required?

**Comment by zamhaq** [comment]
I think that's not a requirement right now. Thanks.

**Comment by gabru-md** [comment]
@stealthanthrax this does not look like a viable issue to me.
as @zamhaq stated, There will be no sessions so no need to do this.
Having links that redirect to the website is, according to me, more than enough!
Cheers!
@zamhaq this issue can be closed.

**Comment by stealthanthrax** [comment]
@gabru-md @zamhaq @ms10398 ok.
