### ISSUE TITLE
Table response have too many responses

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#112]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Table response shows too many rows.

**Expected behavior:**
It should have limited rows.

**Steps to reproduce:**
Type `Universities in India`

Your operating system

Ubuntu 17.04

**Would you like to work on the issue?**

Yes If @zamhaq @gabru-md If you think so it is needed

**Comment by zamhaq** [comment]
@ms10398 thinking of including a `show more` like option?

**Comment by ms10398** [comment]
Yes that could be a good option @zamhaq

**Comment by zamhaq** [comment]
@ms10398 yes sure.

**Comment by zamhaq** [comment]
@ms10398 whats the status on this?

**Comment by ms10398** [comment]
@zamhaq I will make the PR tom I have figured a way for it.

**Comment by gabru-md** [comment]
@ms10398 please update.
