### ISSUE TITLE
After the new features added the dark theme has issue

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#114]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
The side menu doesnt follows dark theme

**Expected behavior:**
It should follow the dark theme
**Steps to reproduce:**
Turn on the dark theme

**Screenshots of the issue**

![screenshot from 2017-10-05 22-38-12](https://user-images.githubusercontent.com/26259547/31240349-04dc2ef8-aa1e-11e7-8839-e4df7a436be2.png)

**Would you like to work on the issue?**
No it can be assigned to anyone

**Comment by sachincool** [comment]
Yes I would like to work on it Thanks
