### ISSUE TITLE
Opening the settings tab in a new window.

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#118]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Settings tab opens in a new tab which makes the user to ultimately leave his work which ultimately destroys the purpose of making a chromebot

**Expected behavior:**
To make the window open in a new window of custom size.

Your operating system
Mac OS

**Would you like to work on the issue?**

Yes , would like to work on this issue.

**Comment by stealthanthrax** [comment]
@zamhaq @ms10398, I am unable to fix this issue properly , Can you guys  assign it someone else?

**Comment by akshatnitd** [comment]
@stealthanthrax @zamhaq @ms10398 I am working on it
