### ISSUE TITLE
To add descriptive logos in susi navbar (UI/UX)

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#120]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

Your operating system
MAC OS

**Would you like to work on the issue?**
 Yes, I would like to work on this issue

**Comment by ms10398** [comment]
This issue can now be closed I think @stealthanthrax as the relevant PR is already merged
