### ISSUE TITLE
Add a clear chat button

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#124]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Stored chat data cannot be deleted unless done through the console. 

**Expected behavior:**
Implement a `button` to clear the stored chat logs.

**Would you like to work on the issue?**
No.

**Comment by ms10398** [comment]
I would like to work on it @zamhaq

**Comment by VRamazing** [comment]
Where should we add this button? The only suitable place that suits me is next to color toggle button or we can add it in the menu bar

**Comment by zamhaq** [comment]
@ms10398 @VRamazing  make the `theme toggle` and `clear chat` as separate drop down on the top right where the `theme toggle` is currently placed.

**Comment by VRamazing** [comment]
@zamhaq  Sounds cool

**Comment by ms10398** [comment]
@zamhaq I will try to implement it that way

**Comment by VRamazing** [comment]
@ms10398 Are you working on this?

**Comment by ms10398** [comment]
I have already made a PR @VRamazing
