### ISSUE TITLE
Link to Contributing.md in Readme.md redirecting to 404

### ISSUE THREAD

**Issue by VRamazing** [fossasia/susi_chromebot#125]
**I'm submitting a ...**  (check one with "x")
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

click on  "here" next to  Read CONTRIBUTING.md at bottom of README.

**Expected behavior:**

Should redirect to contributing file

**Steps to reproduce:**

Contributing.md  doesn't exist in the repo so it must either be created or if its located at some other host then its link should be updated in readme. 
![screenshot from 2017-10-11 00 01 37](https://user-images.githubusercontent.com/9432421/31403679-74b67ccc-ae17-11e7-8bd3-92e0b8b7842c.png)

**Related code:**

**Other information:**

**System information:**

```
Your operating system
```
Linux
**Would you like to work on the issue?**
Yes
Please let us know if you can work on it or the issue should be assigned to someone else.
```

**Comment by stellargo** [comment]
Hi, I would love to work on this! Could you tell me if a contribute.md needs to be written, or we already have it, or we need to redirect it to some fossasia general contributing.md :)

**Comment by techpool** [comment]
@VRamazing Please take a look at the above PR and let me know if this fixes the issue.

**Comment by VRamazing** [comment]
@techpool  Looks good to me
