### ISSUE TITLE
Set text area resizeable to false

### ISSUE THREAD

**Issue by VRamazing** [fossasia/susi_chromebot#128]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Text area to input message can be resized which is a very bad ui

**Expected behavior:**

It should not be resizable by user and overflow should be allowed in case of text overflows

**Steps to reproduce:**

Click on extend icon on lower right corner of message text area and extend to bottom

**Would you like to work on the issue?**
Yes

**Comment by ms10398** [comment]
Please for all the issues related to UI you can make a single UI enchancement issue and not seperate  issues as there are 6-7 small issues only UI related.

**Comment by VRamazing** [comment]
@ms10398 I am gonna update all issues with a single one
