### ISSUE TITLE
Add  right padding to send message button or increase the width of text area .It appears unsymmetric

### ISSUE THREAD

**Issue by VRamazing** [fossasia/susi_chromebot#129]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behaviour:**

Too much space between text-area right corner and send button.Too little space between right corner of send button and extension window

**Expected behaviour:**

For a good UI the bottom component should be somewhat symmetric to the top component.

**Would you like to work on the issue?**
Yes

**Comment by gabru-md** [comment]
@VRamazing it is great to have all these issues and that you are too eager to solve it. But it would be better to have it done under one single PR as they all are just UI Issues nothing else.

**Comment by zamhaq** [comment]
@VRamazing that's almost incomprehensible.

**Comment by gabru-md** [comment]
So kindly donot issue more than one PR  for all the  UI Enhancements

**Comment by VRamazing** [comment]
@gabru-md Multiple issues are created to get feedback on each issue seperately.If you want me to merge them into 1 PR.I can do that.

**Comment by VRamazing** [comment]
@zamhaq  Sorry about that should have added screenshot.Anyways I have fixed the bug.
