### ISSUE TITLE
Login is not responding.

### ISSUE THREAD

**Issue by rupav** [fossasia/susi_chromebot#132]
**I'm submitting a ...**  (check one with "x")
- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Clicking on 'login' from extension dont respond/do anything.
![2017-10-11](https://user-images.githubusercontent.com/20624380/31459231-2f7b5104-aee0-11e7-9fda-8f5103ec0b19.png)

**Expected behavior:**

Redirect to this:
![2017-10-11 1](https://user-images.githubusercontent.com/20624380/31459267-4b336e36-aee0-11e7-9055-abe9f425bdce.png)

**Steps to reproduce:**

**Related code:**

**System information:**

```
Your operating system
```
windows 10
**Would you like to work on the issue?**
Yes

**Comment by zamhaq** [comment]
@rupav the login functionality is not needed. That link will actually be removed.

**Comment by rupav** [comment]
Ok @zamhaq 👍, Closing this issue then.
