### ISSUE TITLE
Add communication channel to readme

### ISSUE THREAD

**Issue by geekyd** [fossasia/susi_chromebot#134]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
There is no information about the gitter communication channel.

**Expected behavior:**
Please add information about gitter channel to readme.md

**Comment by stealthanthrax** [comment]
@geekyd i would like to work on this issue
