### ISSUE TITLE
To add a login feature

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#139]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [s] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
No login feature

**Expected behavior:**
To add a login feature

**Would you like to work on the issue?**
Yes
```

**Comment by stealthanthrax** [comment]
@ms10398 @zamhaq is it required to have a specific color scheme for the form??

**Comment by ms10398** [comment]
@stealthanthrax I think you should go with basic susi themed colors.

**Comment by ms10398** [comment]
@stealthanthrax If you need help I would like to work on it.

**Comment by zamhaq** [comment]
@stealthanthrax what's the progress on this issue?

**Comment by stealthanthrax** [comment]
I was trying to close the previous issue which has been closed now,(adding
descriptive logos),prior to this issue.And now that has been closed, I'll
be adding the pr within a few days.:smile:

**Comment by stealthanthrax** [comment]
@zamhaq @ms10398 @zamhaq ,the ux of login portal is complete , so can i use google/facebook/github authentication with it?

**Comment by zamhaq** [comment]
@stealthanthrax Can you make the PR if you have completed your work. What do you mean by UX portal? You can use google/facebook/Github authentication if it is being used in webchat too. But, first please implement the login feature using susi server api. Please make the PR soon as I need to work on this https://github.com/fossasia/susi_chromebot/issues/165 which depends on this login feature. Mention your progress too. Thanks.

**Comment by stealthanthrax** [comment]
@zamhaq ,since the google/facebook/github authentication are not being used on the web app.So,I was confused on using it and posted a question on gitter channel regarding it. And regarding the pr,i'll be putting it up in the coming week.

**Comment by zamhaq** [comment]
Please try to do it by this week @stealthanthrax. It has already been about two weeks since took it up.

**Comment by ms10398** [comment]
This should be closed as the relevant PR is merged.
