### ISSUE TITLE
Dark theme automatically switches to Light theme

### ISSUE THREAD

**Issue by harshit98** [fossasia/susi_chromebot#142]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behaviour:**
After using the extension in dark mode, closing up popup and re-opening it switches back the theme to light mode.

**Expected behaviour:**
It should not automatically switch from dark mode to light mode.

**Steps to reproduce:**
- Open up the extension and enable dark mode.
- Close the extension and re-open it.
- You will observe that the dark theme gets automatically switched to light theme.

**Would you like to work on the issue?**

No.

**Comment by shubhshrma** [comment]
I'd like to take this up.
