### ISSUE TITLE
Message box not visible in the dark theme

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#145]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Input box not clearly visible.

**Expected behavior:**
To change the color of the message box
<img width="349" alt="screen shot 2017-10-23 at 12 52 51 am" src="https://user-images.githubusercontent.com/29942790/31865446-b3250f5e-b78c-11e7-924c-41645115c6cc.png">

**Would you like to work on the issue?**

Yes
```

**Comment by zamhaq** [comment]
@stealthanthrax this issue already has PR. Thanks.

**Comment by ms10398** [comment]
This can be closed @stealthanthrax @zamhaq
