### ISSUE TITLE
Add suppport for map response

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#157]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
There is no support for map response type till now

**Expected behavior:**
There should be support of map response

**Steps to reproduce:**
Type `Where is India` in the chat

**System information:**

`Ubuntu 17.04`

**Would you like to work on the issue?**
Open for GCI students

**Comment by gabru-md** [comment]
@ms10398 I would like to add this task to GCI-17 as an advanced task. If you have not started working on it please let me know so that I can add this.

**Comment by ms10398** [comment]
I was going to make a PR today night @gabru-md

**Comment by ms10398** [comment]
Yeah sure @gabru-md

**Comment by arnav-mandal1234** [comment]
Hello Sir,
I am a newbie to opensource.Can I take this task?

**Comment by gabru-md** [comment]
Since GCI is over.
I am taking this task up for myself. Will provide a PR within 2 days.

**Comment by gabru-md** [comment]
I'll be using leafletJS for map type response. 
It is Open Source and has a rich api documentation.
Please comment down and ping me if you guys have better alternatives. I'll surely be looking into them
:)
