### ISSUE TITLE
Copy a word directly into susi.

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#158]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Presently there is only one context menu that directly searches a selected word.

**Expected behavior:**
Although it is a great utility, still user might want to simply automatically copy a selected word into susi input field and then edit and finalise the query.

**System information:**

`Ubuntu 17.04`

**Would you like to work on the issue?**

`Yes`

@zamhaq @gabru-md What do you think

**Comment by zamhaq** [comment]
@ms10398 wouldn't that bring some security issues? A user might copy his credit card details and that would  be pasted into susi's input field.

**Comment by gabru-md** [comment]
I agree with @zamhaq as it does pose some security issues as he discussed above.
So i believe this should be left for now until we arrive at a conclusion or alternate idea to make it.
Is it okay @ms10398 ?

**Comment by ms10398** [comment]
There will be different option for copying into susi other than simple copy option.
Whats your thought?

**Comment by hkedia321** [comment]
This feature was dropped down recently in firefox extension. We thought it's an overkill to have both the copy features. User can simply copy and paste the query manually if they want to edit the query before asking SUSI.
