### ISSUE TITLE
Speak now doesnt follows dark theme in the mode

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#159]
**I'm submitting a ...** 
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
When we click on voice input button in dark mode the speak now container doesnt follows dark theme 

**Expected behavior:**
It should follow the dark theme in dark mode

**Steps to reproduce:**
In dark mode click on voice input button

**Screenshot**
![screenshot from 2017-10-25 13-46-42](https://user-images.githubusercontent.com/26259547/31988033-578d86de-b98b-11e7-8a16-f2e10de9fdd7.png)

**System information:**
`Ubuntu 17.04`

**Would you like to work on the issue?**
`Yes`

**Comment by akshatnitd** [comment]
@ms10398 Let me know if you are not working on it, I am free to work on it

**Comment by ms10398** [comment]
I am working on it will make a PR today or till tom morning.
Thanks

**Comment by gabru-md** [comment]
Has this issue been resolved ?

**Comment by ms10398** [comment]
Had been a bit busy due to exams will make a relevant PR soon

**Comment by djmgit** [comment]
@ms10398 if you are busy with some other stuff as you mentioned (and it can definitely happen), you may consider your other co-developer to work on it and collaborate, as it will divide the work load and speed up things, also the PR as well as the issue is open for several days (approx 3 weeks).

**Comment by akshatnitd** [comment]
@ms10398 As the PR for this issue is due for a long time, I am sending the PR I had made for this issue earlier.
