### ISSUE TITLE
Make changes in the manifest for Options page

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_chromebot#161]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Options button is disabled when we right-click on the extension icon.

**Expected behavior:**
Create an options page for the extensions, using the options API, as mentioned in the [MDN page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Options_pages)

**System information:**

```
Arch Linux
```

**Would you like to work on the issue?**
Yes.

**Comment by ms10398** [comment]
@gabru-md @zamhaq Please have a look I didnt find the issue and the relevant PR useful as it opens a new tab with the option to allow mic for the user which we had already shifted to a new popup from the tab.

**Comment by akshatnitd** [comment]
@ms10398 It is just another way of launching the Settings page.

**Comment by gabru-md** [comment]
I agree with @ms10398 as we've already had that feature implemented. And then depreciated it as well. 
@zamhaq is busy with his exams so this must be kept on a hold i guess. He will have a look when he is free.
Thanks !

**Comment by ms10398** [comment]
I think we can close the issue and the referenced PR as well
