### ISSUE TITLE
Follow SUSI Webchat design and move drop down menu to the right

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_chromebot#164]
SUSI Webchat keeps the drop down menu on the right. Also, the button for night mode should move to the "Themes" button (also needs to be changed in SUSI Web chat).

**Comment by ms10398** [comment]
I would like to work on it @mariobehling
I want to ask where should the theme option should be put exactly do you mean to put it in the dropdown.

**Comment by akshatnitd** [comment]
@ms10398 Are you working on it ?

**Comment by ms10398** [comment]
Yes @akshatnitd

**Comment by ms10398** [comment]
This issue is open to claim as I am busy with solving other issues

**Comment by 0x48piraj** [comment]
Claiming!

**Comment by ms10398** [comment]
Yes sure go ahead
