### ISSUE TITLE
Follow SUSI.AI architecture and get chat history from server

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_chromebot#165]
Currently chat history is stored in local storage. This local storage should be synced with the server that keeps SUSI.AI logs. User should be able to log in and have a consistent chat history across devices, e.g. if someone uses SUSI.AI on Android and then switches to the Chrome bot.

Please implement a common approach and ensure the chat is following the existing architecture.

**Comment by zamhaq** [comment]
@mariobehling I have already put up an issue https://github.com/fossasia/susi_chromebot/issues/149. I was working on it but because of exams, I am unable to work much. If anyone else wants to work on it and can provide the `PR` early, please leave a comment here and do so. Thanks.

**Comment by ms10398** [comment]
@zamhaq I am work on this issue as this issue can be implemented now.

**Comment by zamhaq** [comment]
Yeah go for it, it would be good if you provide the PR soon.

**Comment by ms10398** [comment]
Thanks will provide the PR in a day or two.

**Comment by zamhaq** [comment]
@ms10398 have you started working on it? If not then I can work on it now.

**Comment by ms10398** [comment]
You can go ahead I have been busy with GCI and exams

**Comment by stealthanthrax** [comment]
@zamhaq @ms10398 can i work on this issue?

**Comment by ms10398** [comment]
Yes sure!
Give it a try

**Comment by sachincool** [comment]
As the post was inactive i have made the PR, please review. :fire:
