### ISSUE TITLE
Clear all button

### ISSUE THREAD

**Issue by vaibhavsingh97** [fossasia/susi_chromebot#17]
**Current Behaviour:**
There is no option to clear the chats

**Expected Behaviour:**
There should be clear option in the chat

**I want to work on this issue**

**Comment by gabru-md** [comment]
Re clicking the icon clears the chat as the application re-runs. So i beileve this issue is not needed.

**Comment by gabru-md** [comment]
@vaibhavsingh97 can this issue be closed ? 
:)

**Comment by ms10398** [comment]
@vaibhavsingh97 Can this issue be closed

**Comment by vaibhavsingh97** [comment]
@ms10398 @gabru-md Closing since since this is not an issue 😄
