### ISSUE TITLE
Add proper styling to drop-down menu

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_chromebot#176]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
* The dropdown menu icon is too close to the boundary.
* The menu items of drop-down has inappropriate padding and the icons are not at the center.

**Expected behavior:**

* The dropdown icon button needs left padding.
* Add proper padding and make the icons to the center.

**Steps to reproduce:**
Launch the extension and hover on the drop-down menu.

**Screenshots:**
![1](https://user-images.githubusercontent.com/12656846/32417502-d71b8948-c280-11e7-9516-b71d31cd70b7.png)
![2](https://user-images.githubusercontent.com/12656846/32417503-d7531fe8-c280-11e7-92e9-ce53eeeba23a.png)

**System information:**
```
Arch Linux
```

**Would you like to work on the issue?**

```
Yes
```

**Comment by ms10398** [comment]
It is already being handled by https://github.com/fossasia/susi_chromebot/issues/164 so this issue doesnt have relevance.

**Comment by akshatnitd** [comment]
@ms10398 Can I work on that issue?
