### ISSUE TITLE
Fix permissions

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#183]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
The extension has the permission to `Read and change all the data on the websites that you visit`.

**Expected behavior:**
Check if its possible to require fewer permissions and still be fully functional.
![path939](https://user-images.githubusercontent.com/20766601/32857537-24d1b802-ca6e-11e7-9a31-5a051a908a78.png)

**Steps to reproduce:**
Check details on extensions page.

**Related code:**
check `manifest.json` `permission` field.

**Would you like to work on the issue?**
No.

**Comment by ms10398** [comment]
I would like to fix this.
