### ISSUE TITLE
The need to have a separate page for settings option

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#187]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
New features need a proper a separate page

**Expected behavior:**
To make a separate page for settings page

Your operating system

**Would you like to work on the issue?**
Yes

**Comment by stealthanthrax** [comment]
@ms10398 @zamhaq @gabru-md ,only a bit of backend work is pending.Till then could you please suggest design edits?.
This is the proposed design
<img width="1129" alt="screen shot 2017-11-30 at 5 15 43 pm" src="https://user-images.githubusercontent.com/29942790/33429331-653e3f2a-d5f2-11e7-9b39-3d430d570d6f.png">

**Comment by ms10398** [comment]
@stealthanthrax it looks good

**Comment by ms10398** [comment]
Can we add any new feature or should we keep it like this

**Comment by stealthanthrax** [comment]
@ms10398 , suggest any feature that you have in mind?

**Comment by ms10398** [comment]
I was thinking can you add login option and settings page on a single page with seperate tabs or pane
then it would be better what do you think @zamhaq @gabru-md

**Comment by stealthanthrax** [comment]
@ms10398 , i was also thinking of using different tabs for future updates.But can we add them in future PR's?

**Comment by stealthanthrax** [comment]
close via PR #196
