### ISSUE TITLE
To add a variety of voices (of different genders and accents according to the user prference)

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#193]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Susi only has a male voice 

**Expected behavior:**
To have more than one voices

**Would you like to work on the issue?**
  Yes 
```

**Comment by arnav-mandal1234** [comment]
Can I take this task? I would love to work on it.

**Comment by stealthanthrax** [comment]
I have done this task but am facing a small bug , you could help me out with that?

**Comment by arnav-mandal1234** [comment]
ya sure 👍

**Comment by zamhaq** [comment]
@stealthanthrax @arnav-mandal1234 What's going on with this one guys? Quite a long time since it was claimed @stealthanthrax. :sweat_smile:

**Comment by zamhaq** [comment]
@stealthanthrax yes, let someone work on your fork or if they want to work on their own that is fine too. So, this issue is open to anyone.

**Comment by stealthanthrax** [comment]
@zamhaq,it’s fine either ways

**Comment by arnav-mandal1234** [comment]
@stealthanthrax I was not able to fix the bug in your code.
So, I will be making a PR within 2 days including few other issues.

**Comment by stealthanthrax** [comment]
closed via #291
