### ISSUE TITLE
To add a selection of predefined colored themes as in the web app

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#197]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Only light and dark themes are available 

**Expected behavior:**
More than two choices for default themes

**Would you like to work on the issue?**

Yes, I would like to work on this issue.

**Comment by stealthanthrax** [comment]
@zamhaq @gabru-md @ms10398

**Comment by gabru-md** [comment]
I would like to work on this .

**Comment by stealthanthrax** [comment]
@gabru-md , i was working on it, just wanted to ask whether it's required or not. :smile:
