### ISSUE TITLE
Enable like and dislike buttons as in chat.susi.ai

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/susi_chromebot#198]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
There are no like and dislike buttons to get response from the user about a particular message.
![image](https://user-images.githubusercontent.com/8947010/33514335-46945e7e-d778-11e7-840d-99d8a62991a1.png)

**Expected behavior:**

As thre are like and dislike buttons that record user responses from the user, the same should be implemented in the extension.
![image](https://user-images.githubusercontent.com/8947010/33514368-a781cc80-d778-11e7-93f9-dd4d74f8755a.png)

**Steps to reproduce:**

Open the extension in chrome and type in a message.

**System information:**

```
Your operating system: Windows
```

**Comment by stealthanthrax** [comment]
@abishekvashok , i would like to work on this issue

**Comment by abishekvashok** [comment]
@stealthanthrax sure go on.

**Comment by abishekvashok** [comment]
Opened it as part of GCI.
Link to my task: https://codein.withgoogle.com/dashboard/task-instances/6704962555871232/

**Comment by stealthanthrax** [comment]
@abishekvashok , i am not a gci participant . Let the others take it up 😄

**Comment by abishekvashok** [comment]
@stealthanthrax not in my concern.

**Comment by gabru-md** [comment]
I don't have an idea about it. But since GCI is going on i guess it will be great to leave it for the students to pick this task up.

**Comment by stealthanthrax** [comment]
@gabru-md, i'll leave it for the GCI participants and If anyone wants help regarding this issue, he/she can refer my fork . 😄

**Comment by stealthanthrax** [comment]
Okay, since gci is over, I would like to work on this

**Comment by abishekvashok** [comment]
@stealthanthrax pls go on :)

**Comment by gabru-md** [comment]
@ms10398 reopen?

**Comment by gabru-md** [comment]
I will take it as a priority issue and send a PR for the same now.

**Comment by stealthanthrax** [comment]
@gabru-md @ms10398,since this issue was assigned to me and I did what you guys said in the reviews ,hence the issue should be assigned to **me ** again.

**Comment by gabru-md** [comment]
You claimed your issue.
And the changes I requested were only on the frontend.
I never approved your backend changes as I was a bit confused then about the code you wrote. But it still got reviewed and merged. 
You failed to provide a working PR for the issue that you claimed and so it was reverted asap. 
Rest we can have @ms10398 decide who to be assigned :)

**Comment by ms10398** [comment]
@stealthanthrax You can go ahead and if you fail to provide the PR in 2 days
Issue can be took over by @gabru-md

**Comment by gabru-md** [comment]
Ping @ms10398 .
Please let me know as I will have to figure out a way for storing data and finding the API. So If you could let me know that should I start working on this or not ?
It had already been 2+ days and no relevant PR has been provided

**Comment by ms10398** [comment]
As no PR is provided you can go ahead @gabru-md 

I dont think @stealthanthrax will have any issues now with it.

**Comment by stealthanthrax** [comment]
@gabru-md @ms10398 , i was busy in submitting a final summary for codeheat, but it looks like @gabru-md really want's to do it, you can go ahead 😄

**Comment by rupav** [comment]
@gabru-md @ms10398  would like to work on this.
