### ISSUE TITLE
To make certain features login specific

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#199]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
All the existing features are available to every user.

**Expected behavior:**
To make certain features only login specific that provides extra perks to logged in user

**Would you like to work on the issue?**

Yes.

**Comment by ms10398** [comment]
@stealthanthrax you are already working on many other issues you should other devs also work on issues which makes the development process fast there are issues which are stagnant. Just a advice to take the best advantage of Open Source

**Comment by stealthanthrax** [comment]
@ms10398 , I am very excited to be a part of team FOSSASIA and hence keep taking and working on issues 😃

**Comment by ms10398** [comment]
yeah but right now you have already took around 5+ issues which makes other dev not possible to work on those issues.

**Comment by stealthanthrax** [comment]
@zamhaq @ms10398 @gabru-md , should i make the complete settings page login specific ?
