### ISSUE TITLE
The UI Should be more Agile!

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/susi_chromebot#202]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
![feature](https://user-images.githubusercontent.com/5800726/33518231-98296506-d7b7-11e7-949b-5d59da4454dc.gif)
![feature1](https://user-images.githubusercontent.com/5800726/33518232-9d82026a-d7b7-11e7-808b-b45a149359e8.gif)

**Expected behavior:**

It will hold the setting more a little longer to avoid the above situation! :sweat_smile: 

**Steps to reproduce:**

Hover to the vertical-3-dots, which is used to view the options.

**Other information:**

**System information:**

```
Your operating system : Windows
```

**Would you like to work on the issue?**

Not right now. :wink:

**Comment by ms10398** [comment]
There is a issue for moving dropdown to the right and moving theme option into it so maybe this issue would be covered in it!!

**Comment by ms10398** [comment]
https://github.com/fossasia/susi_chromebot/issues/164

**Comment by arnav-mandal1234** [comment]
this is not solved.Can I take this task? @ms10398

**Comment by 0x48piraj** [comment]
@arnav-mandal1234 
Yes! Go on :+1:
