### ISSUE TITLE
Auto-close extension window

### ISSUE THREAD

**Issue by Jerry2001** [fossasia/susi_chromebot#206]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
The extension window closes everytime I switch to a different tab or application.

**Expected behavior:**
The extension window should be kept opened even when I switch to a different tab or application.

**Other information:**
Sorry, I don't really know how to program an extension but my friend and I find it really annoying when the extension window constantly closes when we open switch to a different tab or application.

**Your operating system**
Window 7

**Would you like to work on the issue?**
No :<

**Comment by zamhaq** [comment]
@Jerry2001 Thanks for reporting. But I think Chrome does not allow to do that. Therefore, closing this issue.
