### ISSUE TITLE
Enable sent ticks on messages

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#207]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

No `sent ticks` on messages which are successfully sent to the server.

**Expected behavior:**
Enable sent ticks as done in susi webchat.

```
Ubuntu 16.04
```

**Would you like to work on the issue?**
No.

**Comment by ms10398** [comment]
I would like to work on it just as the susi chromebot starts interacting with the server

**Comment by zamhaq** [comment]
@ms10398 My exams are starting tomorrow, if I don't make a `PR` by 7th then #165 should be open. You can work on it if you'll be free.

**Comment by ms10398** [comment]
Will try to same exams going on here too :disappointed: 
But will try to work :smile:

**Comment by rupav** [comment]
can I do it? @ms10398 ?

**Comment by ms10398** [comment]
Actually right now susi is not syncing messages with server thats why this issue has to wait for it to interact with it.
You can work on the issue of syncing chat history from server as right now noone is working on it.

**Comment by ms10398** [comment]
I will work on it and make a relevant PR soon.
