### ISSUE TITLE
Organise code and fix indendation

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#208]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
All the files are clustered now

**Expected behavior:**
To put all files in separate folder (diff folders for js and css folders)

**Would you like to work on the issue?**

Yes

**Comment by ms10398** [comment]
@stealthanthrax We had already put up as GCI task

**Comment by stealthanthrax** [comment]
But, i made a pr few days back

**Comment by ms10398** [comment]
About what

**Comment by stealthanthrax** [comment]
Regarding this issue , assuming it to be a quick pr, i didn't create an issue

**Comment by ms10398** [comment]
Regarding which issue

**Comment by stealthanthrax** [comment]
@ms10398 , i can't understand your query

**Comment by ms10398** [comment]
Oh okay got it!! Sorry
