### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#21]
Chrome is failing to load the unpacked extension.

![failed](https://user-images.githubusercontent.com/20766601/30752823-18991494-9fdb-11e7-8c02-ecbcf0893f8f.png)

Yes I would like to work on this.

**Comment by gabru-md** [comment]
Sorry zamhaq it is an error on my side. I forgot to add the icon.png file in my last commit.
If you could let me upload it ?

**Comment by zamhaq** [comment]
Yeah sure. I was about to do the same :smile: anyways go ahead !

**Comment by ms10398** [comment]
I think i can upload icon.png with my fix of issue of return key so that two issues will get solved by one PR

**Comment by ms10398** [comment]
@zamhaq @gabru-md

**Comment by zamhaq** [comment]
@ms10398 let him do it because he has it all setup. :smile:

**Comment by ms10398** [comment]
Okay sure go ahead
