### ISSUE TITLE
It needs an avatar!

### ISSUE THREAD

**Issue by ducminh198** [fossasia/susi_chromebot#210]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Talking to just a name is boring.
 
**Expected behavior:**

I think Susi should have an avatar on the corner.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

```
Your operating system
```

**Would you like to work on the issue?**
No, I wouldn't.

Please let us know if you can work on it or the issue should be assigned to someone else.
```

**Comment by prateekiiest** [comment]
Please close this issue
