### ISSUE TITLE
Intergration of Calculator in SUSI bot

### ISSUE THREAD

**Issue by awesometushar000** [fossasia/susi_chromebot#212]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Expected behavior:**

There should be a calculator in SUSI bot which add up the things for us.
Can we try to add https://github.com/fossasia/Ember_Simple_Calculator to SUSI?

**Comment by stealthanthrax** [comment]
I think we can add/edit some skills , but adding a feature will only make the extension heavy .@zamhaq @gabru-md @ms1038

**Comment by zamhaq** [comment]
@stealthanthrax that should be done through skills.

**Comment by ms10398** [comment]
Yes agreed with both of you @stealthanthrax @zamhaq

**Comment by gabru-md** [comment]
I guess there is a Woflram Alpha skill for computing mathematical expressions. You might want to check that out on susi.

**Comment by zamhaq** [comment]
@gabru-md susi can already perform calculations. This issue can be closed?
