### ISSUE TITLE
Adding the a login through facebook sdk

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#214]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Only able to login through susi server

**Expected behavior:**
To be able to login via face 

**Related code:**

Using the facebook sdk

Please let us know if you can work on it or the issue should be assigned to someone else.
Yes

**Comment by mariobehling** [comment]
Adding to other networks should happen through the server. Please open an issue in SUSI.AI Server.
