### ISSUE TITLE
To shift the dark theme toggler in themes page

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#219]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
The theme toggle button is on the top left.

**Expected behavior:**
To add it in the menu inside the drop-down menu like in chat.susi.ai

**Would you like to work on the issue?**

Yes

**Comment by gabru-md** [comment]
Seems to me as am irrelevant issue.
Keeping it on the popup.html guves more accessibility  to the extension. And i gueas that this idea must be dropped.

**Comment by stealthanthrax** [comment]
@gabru-md , I agree that it increases accessibility but since we were trying to make cbot paralle to web app , I though this issue must be created.

**Comment by stealthanthrax** [comment]
@gabru-md @ms10398 @zamhaq @akshatnitd , what should be done here now?

**Comment by gabru-md** [comment]
I still hold my point.

**Comment by arnav-mandal1234** [comment]
I also think this issue is irrelevant.I am up with @gabru-md

**Comment by gabru-md** [comment]
@ms10398 close this ?
