### ISSUE TITLE
When asked to show image it shows URL instead of the image

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#22]
**Expected Behavior**

It should display the image

**Actual Behaviour**

It shows the URL

Screenshot is attached below
![screenshot from 2017-09-22 21-13-16](https://user-images.githubusercontent.com/26259547/30752880-4f609952-9fdb-11e7-8ac0-530e956e8da2.png)

**Comment by gabru-md** [comment]
These are formatting issues and can be easily dealt with after checking the JSON.
I will claim this issue as of now!
Thanks @ms10398 for reporting it to us!
