### ISSUE TITLE
To create a feature allowing to change password directly through the chromebot

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#220]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Only being able to change the password via the main app

**Expected behavior:**
To be able to change password from the chromebot

**Related code:**

Using susi api and jquery 

**Would you like to work on the issue?**
Yes

**Comment by ms10398** [comment]
Can I work on it

**Comment by ms10398** [comment]
As I was free and you are already assigned to many issues

**Comment by stealthanthrax** [comment]
I have partially worked on it and will complete it soon 😄.And  regarding the issues, only one is pending and will make a PR tonight 😄

**Comment by ms10398** [comment]
Okay thats good

**Comment by stealthanthrax** [comment]
@ms10398 @zamhaq , since the PR made on this is beyond repair ,I'll make a new PR in 1-2 days
