### ISSUE TITLE
To add a loading feature in the login form

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#222]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
The login feature while loading gives no indication

**Expected behavior:**
To add a loader gif or a self-created pre-loader

**Would you like to work on the issue?**

**NO**

**Comment by akshatnitd** [comment]
Claiming :rocket:

**Comment by akshatnitd** [comment]
I have made a PR for it. Will send a PR, once #224 gets merged :smile:
