### ISSUE TITLE
A bug in the login form

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#227]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Currently, the user log's out just when the page is refreshed

**Expected behavior:**
Logged in even after refreshing

**Steps to reproduce:**
Log-in and then refresh the page

Your operating system
OSX

**Would you like to work on the issue?**
Yes

**Comment by arnav-mandal1234** [comment]
Hello Sir,
I am a newbie to opensource.Can I take this task?

**Comment by stealthanthrax** [comment]
This task has an open PR with reference to it
