### ISSUE TITLE
Sync theme settings if user is logged in

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#228]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Currently, if the user is logged in and changes the theme setting the theme settings is not saved on the server.

**Expected behavior:**
If the user is logged in and changes the theme setting the theme settings must be saved on the server.

**Would you like to work on the issue?**
Yes

**Comment by sachincool** [comment]
@ms10398  this issue got over 20 days, Can i work on it .. if you're a bit stuffed at this moment ?

**Comment by ms10398** [comment]
Okay sure go for it!
