### ISSUE TITLE
Add option for recover password

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#229]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
There is no such feature right now

**Expected behavior:**
User can request to reset password from chromebot

**Would you like to work on the issue?**
Yes

**Comment by arnav-mandal1234** [comment]
Can I take this?
