### ISSUE TITLE
Add option to signup from the chromebot

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#230]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Currently no option for signup is there

**Expected behavior:**
Add option of signup through signup

**Would you like to work on the issue?**
Yes

**Comment by arnav-mandal1234** [comment]
can I take this task?

**Comment by ms10398** [comment]
I was going to send PR's for all my issues today.
Thanks there are many issues feel free to work on them
