### ISSUE TITLE
Login is not working

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#231]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
JS file to login page is not linked

**Expected behavior:**
JS file should be linked so that the login page works

**Steps to reproduce:**
User is not able to login

**Screenshot**
![screenshot from 2017-12-17 19-35-45](https://user-images.githubusercontent.com/26259547/34080348-43464ad4-e362-11e7-9ba8-0e810f92f7d5.png)

**Would you like to work on the issue?**
Yes

**Comment by gabru-md** [comment]
That might just be an error for you since i am not encountering any such error. Please check and notify before proceeding :+1:

**Comment by ms10398** [comment]
I checked it
Please update your fork

**Comment by gabru-md** [comment]
Sure. Will let you knwo once i do.

**Comment by ms10398** [comment]
Okay sure let me know soon as i am already ready with the PR

**Comment by stealthanthrax** [comment]
@ms10398, this issue is fixed in pr adding the option of changing the password

**Comment by ms10398** [comment]
okay but i saw there was no notification please do norify before doing so that there is no confusion

**Comment by ms10398** [comment]
Close it when your PR merges

**Comment by stealthanthrax** [comment]
Ok,sorry.Will do it from the next time

**Comment by stealthanthrax** [comment]
:smile

**Comment by gabru-md** [comment]
close this ?

**Comment by sachincool** [comment]
@gabru-md  Exactly right !  Please close this @ms10398
