### ISSUE TITLE
To include a documentation of susi_server 

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#234]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
No documentation regarding the susi API is present in the chromebot docs

**Expected behavior:**
To add docs like in the web chat and susi_server, making it easy for the newcomers to inderstand the code 

**Would you like to work on the issue?**

No,GCI task

**Comment by ms10398** [comment]
I dont think this is needed as there is no specific feature or API to document here.

**Comment by ms10398** [comment]
And API is documented in chat.susi.ai very well

**Comment by ms10398** [comment]
Exactly docs like what you are talking can you provide a example

**Comment by stealthanthrax** [comment]
@ms10398 , I was referring to docs like these: https://github.com/fossasia/chat.susi.ai/blob/master/docs/ACCOUNTING.md,

But these docs are **specifically** for chat.susi.ai, I wanted to make one for the chromebot, so that a new contributor does not have to look the docs of other projects.

**Comment by ms10398** [comment]
I know that doc but as we see that doc shouldnt be included in this project as we are using it and not creating it
Still @gabru-md @zamhaq @mariobehling Whats your views

**Comment by zamhaq** [comment]
There is no much need for the docs. The `API` we are using as mentioned by @ms10398 are not created by us. We can have links that points to those API docs. Other things about the features that we provide might be included, but that can be done by GCI students and I think we should have this as a GCI task. About the code documentation,  there is already a GCI task I think where it is mentioned to comment and make documentation for the code. These are my views. Rest depends on you guys. 😁

**Comment by stealthanthrax** [comment]
@zamhaq , this seems cool,we can either link this issue to the gci one and keep it open till it is solved or update the gci task itself?

**Comment by gabru-md** [comment]
@stealthanthrax there seems a lot of issues that you have taken up. kindly refrain from taking more than one issue at once to encourage your peers to work on them as well.
:+1:

**Comment by gabru-md** [comment]
There us no need to add it. Susi server already has everything.
@ms10398 please close this issue
