### ISSUE TITLE
Adding the option to change the color of the message pane

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#238]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
No feature to change color of the message pane

**Expected behavior:**
To allow custom colors for the message pane

**Would you like to work on the issue?**

No

**Comment by gabru-md** [comment]
I think this issue is easy and can be done by a student during GCI ?
If nobody takes it up then it can be assigned to you?

**Comment by stealthanthrax** [comment]
but , to add it as a gci issue , it should be approved in the docs, but since there many beginner issues which are still untouched, so, we can try waiting for its approvall?

**Comment by gabru-md** [comment]
students are only working on anything else than the GCI websites so if we could create some basic tasks for them to encourage them, it would be just great!

rest is upto you. :)

**Comment by arnav-mandal1234** [comment]
Hello Sir,
I am a newbie to opensource.Can I take this task?

**Comment by stealthanthrax** [comment]
@arnav-mandal1234 , go ahead.

**Comment by arnav-mandal1234** [comment]
@stealthanthrax  what do you mean by message pane? can you elaborate? which part if the message pane?

**Comment by gabru-md** [comment]
By message panes he means the bubble in which messages appear.
