### ISSUE TITLE
Export to JSON file does not export the previousy had chats

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#241]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Does not export previous chat data

**Expected behavior:**
Should export all chat data

**Steps to reproduce:**
1. Open chromebot
2. Select Export from menu

**System information:**
Ubuntu 16.04

**Would you like to work on the issue?**
No.

**Comment by stealthanthrax** [comment]
I would like to work on it

**Comment by zamhaq** [comment]
@stealthanthrax how many issues are you assigned to currently?

**Comment by stealthanthrax** [comment]
@zamhaq , only one whose PR is yet to be made

**Comment by zamhaq** [comment]
@stealthanthrax sure go ahead

**Comment by gabru-md** [comment]
@zamhaq Please use `Squash and merge` whenever merging a new PR.
Else it gives an unclear commit history.
See here: https://github.com/fossasia/susi_chromebot/commits/master

Cheers!

**Comment by arnav-mandal1234** [comment]
Hello Sir,
I am a newbie to opensource.Can I take this task?

**Comment by gabru-md** [comment]
sure @arnav-mandal1234

**Comment by stealthanthrax** [comment]
@gabru-md ,this issue is assigned to me
