### ISSUE TITLE
Themes not working

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#242]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Changing themes has stopped working

**Expected behavior:**
Clicking on submit button should change the theme

**Other information:**
It was working before PR #240 

Your operating system
OS X

**Would you like to work on the issue?**

No

**Comment by stealthanthrax** [comment]
@ms10398 @zamhaq @gabru-md , please have a look.

**Comment by ms10398** [comment]
Wait I will send a quick fix of it soon

**Comment by ms10398** [comment]
Fixed it!
Have a look
