### ISSUE TITLE
Showing error in logging using bootstrap alert instead of alert.

### ISSUE THREAD

**Issue by saikat041** [fossasia/susi_chromebot#246]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [ x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
If there is any error in logging then it is shown using alert.

**Expected behavior:**
The error will be shown using bootstrap alert class in the login page itself
![screenshot 2](https://user-images.githubusercontent.com/19255785/34402395-397f8c32-ebc7-11e7-939e-0cdf9573dce0.png)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**
Windows 10

```

Your operating system
```
Windows 10
**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.
```
Yes I can work on it

**Comment by saikat041** [comment]
I will send PR plz review it

**Comment by arnav-mandal1234** [comment]
Can I take this task?

**Comment by duttaditya18** [comment]
@saikat041 Go ahead.

**Comment by stealthanthrax** [comment]
what's the status @saikat041 ?

**Comment by saikat041** [comment]
I created a pull request about 15 days ago. But it never got merged.Now again its having merge conflicts.

**Comment by saikat041** [comment]
@stealthanthrax

**Comment by stealthanthrax** [comment]
okay , my bad

**Comment by saikat041** [comment]
@stealthanthrax what should i do now.

**Comment by ms10398** [comment]
You can resolve the conflicts and ping me up.
I will review your PR

**Comment by saikat041** [comment]
Ok @ms10398
