### ISSUE TITLE
Export icon mismatch with others

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/susi_chromebot#249]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
-current icon doesn't match with others

**Expected behavior:**
-uniform icons

**Steps to reproduce:**
-change the icons

**Would you like to work on the issue?**
Yes

**Comment by stealthanthrax** [comment]
@YashKumarVerma , what is it that is not matching?

**Comment by YashKumarVerma** [comment]
The export icon color mismatches

**Comment by YashKumarVerma** [comment]
! [https://user-images.githubusercontent.com/14032427/34360826-6d2701b6-ea8a-11e7-90ad-be0318673c55.png] (https://user-images.githubusercontent.com/14032427/34360826-6d2701b6-ea8a-11e7-90ad-be0318673c55.png)

**Comment by arnav-mandal1234** [comment]
can I take this issue?

**Comment by YashKumarVerma** [comment]
I am working on it. Would be throwing in a pr in a few hours

**Comment by gabru-md** [comment]
What is the status of this issue ?

**Comment by arnav-mandal1234** [comment]
can I take it?

**Comment by YashKumarVerma** [comment]
I think someone else can go on with this one. I'm a bit occupied with labyrinth.

**Comment by arnav-mandal1234** [comment]
Then may I take this task?

**Comment by akshatnitd** [comment]
@arnav-mandal1234 Yes, you may go ahead with it

**Comment by gabru-md** [comment]
In case if no one responds then you can simply write `Claiming` and start working if the issue has not been dealt with for quite long. 
@arnav-mandal1234 :)
