### ISSUE TITLE
Display error message when unable to connect to susi api

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#25]
**Actual Behaviour**
When message is sent, if susi_chromebot fails to connect to SUSI api then SUSI does not responds anything  and stay idle.
![error](https://user-images.githubusercontent.com/20766601/30761247-2c3f6a6e-9ffb-11e7-8004-cf5e5b13877e.png)
**Expected Behaviour**
Show **"could not connect"** message to user.

**Would you like to work on this ?**
Yes.

**Comment by gabru-md** [comment]
It would be better to show 
"Some Error Occured" 
or
"Sorry! Susi is busy" <- this seems cool to me.
Rest is up to you.
Cheers. Thanks for the issue.

**Comment by zamhaq** [comment]
@gabru-md I will try to check the error code. If its `403` I think its better to report `unable to connect`. `Some error occured` does not give very specific info to `user`.
Thanks for suggestion :+1:
