### ISSUE TITLE
Create options page

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#252]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Settings page opens in a separate window through the extension URL.

**Expected behavior:**
Follow a more standard way of setting up extensions through the `options` page.

![options_page](https://user-images.githubusercontent.com/20766601/34429326-d346ae26-ec7c-11e7-96ed-af642ecc9ab1.png)

Creating the options page will create a button next to the extension as shown in the second extension in the picture above.

**Other information:**
Follow the chrome extension docs on `options` page.

**System information:**
Ubuntu 16.04

**Would you like to work on the issue?**
No.

**Comment by ms10398** [comment]
What you want us to add to the options page?
There is a page should we change it into options page
Whats your thought

**Comment by gabru-md** [comment]
I do no get what is it about ?

**Comment by zamhaq** [comment]
@ms10398 sure do that. @gabru-md Check the second extension in the screenshot above, I think our settings should also be option page, that is the standard way to store settings for extensions.

**Comment by gabru-md** [comment]
Can I work on this? I would like to try my hands on this
and btw please see my PR #248

**Comment by zamhaq** [comment]
@gabru-md sure anytime.

**Comment by gabru-md** [comment]
Should we also remove the `settings` link from chromebot, that actually opens the `options.html` ?
or keep it as well ?

**Comment by ms10398** [comment]
Yes Thats what I was thinking 
Sure go ahead @gabru-md
