### ISSUE TITLE
Add google font link for Lato font

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#26]
The `style.css` file has `body font` set to `Lato` but it is not imported anywhere in `popup.html`.
Add google link for Lato font.
Thanks.

**Comment by AshishkrGoyal** [comment]
@zamhaq can i work on this issue??
Thanks in advance 😄

**Comment by gabru-md** [comment]
Sure @AshishkrGoyal
Go ahead.

**Comment by AshishkrGoyal** [comment]
@zamhaq @gabru-md 
please preview this PR #27 for this issue 👍 

Thanks
