### ISSUE TITLE
An error in console

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#261]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
open the cbot and inspect the console

**Expected behavior:**
no issue

**Steps to reproduce:**

**Related code:**

<img width="862" alt="screen shot 2018-01-05 at 8 00 36 pm" src="https://user-images.githubusercontent.com/29942790/34613302-49228166-f253-11e7-9ffd-88d2bd36e18f.png">

Your operating system
OSX

**Would you like to work on the issue?**

NO

**Comment by arnav-mandal1234** [comment]
Can I take this?

**Comment by stealthanthrax** [comment]
Go ahead

**Comment by gabru-md** [comment]
closing this since this has been done already!
