### ISSUE TITLE
To add a surge dependency

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#269]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Currently one has to add a screenshot or add a gif after creating his PR

**Expected behavior:**
To add a working link like chat.susi.ai

**Related code:**
Adding surge package or something similar

Your operating system
OSX

**Would you like to work on the issue?**
YES

**Comment by ms10398** [comment]
It is a chrome extension so when deployed using surge many of its feature behave different 
So is adding surge a good option?

**Comment by gabru-md** [comment]
Why surge ? 
I mean this is a chrome extension if it is deployed it will give bad results already and will not be a good measure to a gif or image. As Mohit said manys features will not work properly and hence this idea is drop-able.

Moreover we have to make a chromebot and not another chat.susi.ai so i suppose there is no need of surge deployment.

**Comment by stealthanthrax** [comment]
@ms10398 @gabru-md I am not in favor of using **particularly** surge but a package the helps us provide test links.
We can use another package, if you have any suggestions?

**Comment by gabru-md** [comment]
This issue that you have created was considered back when we started contributing . We had a problem of UI testing and all but travis could not be used for testing UI as UI for chrome extensions does not scale well oas browser pages.
Therefore , considering this as the same we can skip this issue. You may deploy it anywhere but the problem will still remain the same. Therefore chromebot requires extensive testing schemes of doing manually.
I guess you understand

**Comment by ms10398** [comment]
And I am thinking of some solution for it maybe implement it just as GCI is over.
