### ISSUE TITLE
[BUG] "cannot read property : actions" with infinite wait

### ISSUE THREAD

**Issue by YashKumarVerma** [fossasia/susi_chromebot#271]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Start a conversation
ask for something related to some location 
> where in vietnam 
**breaks**, infinite wait.

**Expected behavior:**
either show location or say something

**Steps to reproduce:**
Check the scripts

**System information:**
Google Chrome

**Would you like to work on the issue?**
No

# Problem 
![susichromebot](https://user-images.githubusercontent.com/14032427/34906181-a2011cc6-f88d-11e7-87e3-035a104a714d.gif)

**Comment by stealthanthrax** [comment]
i would like to have a try

**Comment by gabru-md** [comment]
`Where in vietnam` will not produce any search result

**Comment by gabru-md** [comment]
It is an error in query i guess.

**Comment by gabru-md** [comment]
@ms10398 please comment

**Comment by ms10398** [comment]
It is a server related bug according to me.

**Comment by rupav** [comment]
this has been solved in https://github.com/fossasia/susi_chromebot/pull/374.
@ms10398 @gabru-md @YashKumarVerma you can close this issue.

**Comment by ms10398** [comment]
Thanks @rupav
