### ISSUE TITLE
Add Hound CI

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/susi_chromebot#272]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [x] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Currently, Hound CI is not present in the repo.
**Expected behavior:**

Adding houndCI in the repo, will help us to review the code for the violation of code styling.
**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

```
Your operating system
```

**Would you like to work on the issue?**

Yes, I wanna work on this.
```

**Comment by gabru-md** [comment]
Close this @ms10398 @zamhaq
