### ISSUE TITLE
Wrong timestamp shown after syncing message with server

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#277]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
After syncing the messages from server, Timestamp shown is wrong.

**Expected behavior:**
Timestamp should be exact.

**Steps to reproduce:**
Message something from chat.susi.ai after login and then login in Chromebot and check the timestamp

**System information:**
```
Ubuntu 17.10
```

**Would you like to work on the issue?**
Yes I am

**Comment by arnav-mandal1234** [comment]
Can I take this?
