### ISSUE TITLE
Adding like and dislike buttons

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#278]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
No like and dislike buttons

**Expected behavior:**
To add like and dislike buttons

**Would you like to work on the issue?**
Yes

**Comment by ms10398** [comment]
Duplicate https://github.com/fossasia/susi_chromebot/issues/198
