### ISSUE TITLE
Chromebot closes on clicking mic icon

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#282]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Chromebot closes by clicking on mic icon

**Expected behavior:**
To display warning in some other way

**Steps to reproduce:**
open cbot and click on the mic icon

Your operating system
OSX

**Would you like to work on the issue?**

Yes

**Comment by ms10398** [comment]
Can you please check again as it is working for me
@gabru-md Can you have a check if it is working for you with the updated branch

**Comment by gabru-md** [comment]
@stealthanthrax There is no problem here on my side. Can you please make sure that it is a legit bug before proceeding?  As it just might save your time :)

**Comment by stealthanthrax** [comment]
@gabru-md @ms10398 , this is a legit issue , I confirmed it by cloning the master.Probably a MACos specific bug .

**Comment by gabru-md** [comment]
This project is WebBrowser specific. And therefore I guess that any bug that is caused to you must be caused to atleast someone else. Since there is no one ( Windows and Linux ) that has any error therefore I suppose it is an error from your side.
As I said it is chrome specific application therefore having a OS specific bug is very weird.

**Comment by stealthanthrax** [comment]
@gabru-md , I have checked this on **2 different MacBooks running different versions of OSx** and am facing the same issue.Probably chrome works differently on OSx

**Comment by stealthanthrax** [comment]
@gabru-md @ms10398 @zamhaq , can we use push notifications instead of alert type response?
