### ISSUE TITLE
To add a feature of show password in login form

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#283]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
No option of login form

**Expected behavior:**
To add an option to show password in login form like Amazon.

**Would you like to work on the issue?**

Yes

**Comment by gabru-md** [comment]
I guess there are a lot of redundant issues that have been created in the past.
@ms10398 please comment

**Comment by ms10398** [comment]
I think you should finish issues and let others claim and when you are with all PR's made then you should claim an issue. Try to stick to best practices as much as you can :+1:

**Comment by gabru-md** [comment]
This feature is not a priority issue and can be given to a new comer. @ms10398 please add a New-Comer and Easy-Pick label to it.

**Comment by stealthanthrax** [comment]
@ms10398 @gabru-md , please could you explain this conversation?

**Comment by ms10398** [comment]
It's a very easy task which can be used to invite newcomers to work on development and as you are an `Experienced Dev` you can focus on advanced issues.

**Comment by arnav-mandal1234** [comment]
Can I take this? and can someone explain to me what I have to do exactly?

**Comment by stealthanthrax** [comment]
@arnav-mandal1234 , i was about to send a PR within 1-2 days

**Comment by ms10398** [comment]
If you fail to provide PR within one or two days @stealthanthrax 

The issue will be assigned to @arnav-mandal1234
