### ISSUE TITLE
support susi_chromebot with other browsers like firefox, microsoft edge etc

### ISSUE THREAD

**Issue by luckykumardev** [fossasia/susi_chromebot#284]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
currently, this extension is online supported by chrome 

**Expected behavior:**
we can use this extension for different browsers also.
![browser](https://user-images.githubusercontent.com/32070019/35139820-a9094154-fca9-11e7-8cf1-377a337413b3.png)

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

```
Your operating system
```

**Would you like to work on the issue?**

yes i want to work on this issue

**Comment by gabru-md** [comment]
We already have a firefox bot :)

**Comment by luckykumardev** [comment]
oh, i haven't seen that.
then I think I should close this issue..
