### ISSUE TITLE
SUSI speaking every message from the start on re-login after re-install

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#289]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Bot speaks out every reply from the start on re-install/re-login.

**Expected behavior:**
Do not speak out on re-login/re-install. Only speaks for currently sent messages.

**Steps to reproduce:**

1. Delete extension.
2. Re-install extension.
3. Add some messages.
4. Login and open extension.

**Would you like to work on the issue?**
No.

**Comment by ms10398** [comment]
I will like to give it a try

**Comment by gabru-md** [comment]
Yes I had this bug but thought that it was just me.
Will be glad to have it solved.
Good luck @ms10398

**Comment by arnav-mandal1234** [comment]
Can I take this? @gabru-md @ms10398

**Comment by ms10398** [comment]
Yes @arnav-mandal1234 You can go ahead

**Comment by gabru-md** [comment]
Yes please. Go ahead

**Comment by rupav** [comment]
I would like to take this up. @gabru-md @zamhaq
