### ISSUE TITLE
JSLint Errors in script.js file

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#30]
Script.js file has several JSLint Errors

![screenshot from 2017-09-23 13-54-41](https://user-images.githubusercontent.com/26259547/30771515-0c92d914-a067-11e7-8a87-18a82cf76fc5.png)

Yes I would like to work on this and make a relevant PR soon.

**Comment by zamhaq** [comment]
@ms10398 Fixing just those bits of code won't be very much effective. Also, not everyone might use eslint/jslint. However, you can integrate **eslint**(use airbnb style guide) into the project if other **contributors** don't have any problem. @gabru-md What do you think ?

**Comment by gabru-md** [comment]
It would be better to integrate Codacy as all other fossasia projects are using Codacy as their primary code checking CI.
@zamhaq I am currently working on it. Was a bit busy due to exams. Will do it and send a PR soon.
Will let you know if I can't

**Comment by ms10398** [comment]
Yes it would be better to integrate codacy in the project so the code is well maintained 
I just fixed the errors till now. because after we integrate codacy we will have to fix those errors.

**Comment by gabru-md** [comment]
@zamhaq we can merge this. And then I'll work upon codacy and travis integration.  :+1:

**Comment by ms10398** [comment]
Yes we should integrate codacy soon
So that our code is well maintained

**Comment by zamhaq** [comment]
@ms10398 @gabru-md great :+1:

**Comment by ms10398** [comment]
Then go ahead for the merge :smile:
