### ISSUE TITLE
Adding custom tests using MOCHA.js

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#300]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
A reference to issue number #172 

**Would you like to work on the issue?**

Yes

**Comment by ms10398** [comment]
Actually it can be considered duplicate as both are writing tests! #172 

Can you explain any difference! @stealthanthrax

**Comment by stealthanthrax** [comment]
@ms10398 , in this I am just referring the API .Wheather we should use it or not.

**Comment by gabru-md** [comment]
Mocha and Chai are for API testing.
And these tests should be for susi-server and not for chromebot.

@stealthanthrax can you please elaborate how are you going to use mocha for testing chromebot ?

**Comment by zamhaq** [comment]
Closing this as `no elaboration provided and suggested solution is irrelevant`.
