### ISSUE TITLE
Make a better color scheme for login page.

### ISSUE THREAD

**Issue by ashupednekar** [fossasia/susi_chromebot#301]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [ ] feature request
- [x] enhancement
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Poor color scheme

**Expected behavior:**

Better Color scheme
![image](https://user-images.githubusercontent.com/25405037/36773409-8343da60-1c7f-11e8-8d0d-f8bf1057d400.png)

**Steps to reproduce:**
Try using gradients...

**Related code:**
![image](https://user-images.githubusercontent.com/25405037/36773453-ad8e5f16-1c7f-11e8-9f4c-44254693f36d.png)

```
insert any relevant code here else remove this section
```

**Would you like to work on the issue?**
YES

Please let us know if you can work on it or the issue should be assigned to someone else.
```

**Comment by ms10398** [comment]
We intentionally kept those colours as It followed Susi web client and desktop client colour scheme.

Thanks! @ashupednekar

**Comment by ashupednekar** [comment]
By the way, I would love to modify the colors for the web and desktop
platforms as well...
That way the color scheme can be both consistent and pretty. :)
On Feb 28, 2018 4:28 PM, "Mohit Sharma" <notifications@github.com> wrote:

Closed #301 <https://github.com/fossasia/susi_chromebot/issues/301>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/susi_chromebot/issues/301#event-1496447005>,
or mute the thread

**Comment by ms10398** [comment]
I am not sure if thats our focus for now

Still there are many other features which are needed to implemented and issues are there it would be a lot better if you like to give them a try.

**Comment by ashupednekar** [comment]
Sure, thanks. :)
