### ISSUE TITLE
Make a better color scheme for signup page.

### ISSUE THREAD

**Issue by ashupednekar** [fossasia/susi_chromebot#303]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [ ] feature request
- [x] enhancement
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
poor color scheme
![image](https://user-images.githubusercontent.com/25405037/36774336-ae2c91fa-1c83-11e8-992a-ae6924fd3a7e.png)

**Expected behavior:**

Better color scheme

**Steps to reproduce:**

Try Gradient...

**Related code:**
![image](https://user-images.githubusercontent.com/25405037/36774382-cdeec288-1c83-11e8-8019-f5ec8580cd8c.png)

**Would you like to work on the issue?**
YES

Please let us know if you can work on it or the issue should be assigned to someone else.
```

**Comment by ms10398** [comment]
We intentionally kept those colours as It followed Susi web client and desktop client colour scheme.

Thanks! @ashupednekar
