### ISSUE TITLE
Update 'Working GIF' for susi extension

### ISSUE THREAD

**Issue by prateekiiest** [fossasia/susi_chromebot#304]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Current SUSI gif looks like this
https://github.com/fossasia/susi_chromebot/blob/master/susi_chromebot.gif

but since some layout of the chromebot has changed, it needs to be updated.
![screenshot 115](https://user-images.githubusercontent.com/16035442/41113933-9c373106-6aa0-11e8-9898-5333b28a6690.png)

**Expected behavior:**

![screenshot 116](https://user-images.githubusercontent.com/16035442/41113940-a0b97252-6aa0-11e8-827d-9c8a7d5e023c.png)

**Steps to reproduce:**

Just update the gif.

**Related code:**
NA
```
insert any relevant code here else remove this section
```
NA
**Other information:**

NA
**System information:**

NA
```
Your operating system
```
Linux
**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.
```
I would like to but someone with good gif recorder might be more helpful

**Comment by gabru-md** [comment]
@prateekiiest please go ahead if you wish to. :+1:
If you need help then you can use OBS to record the video of the chromebot and then convert it into a GIF using some or the other online website.
Cheers!
