### ISSUE TITLE
Duplicate Code

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#310]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

Duplicate code doing the same task exists.

**Expected behavior:**

Duplicate code should not exist.

**Related code:**

```
if(micAccess) {
    micAccess.addEventListener("click", () => {
        navigator.webkitGetUserMedia({
            audio: true
        }, function (stream) {
            stream.stop();
        }, function () {
            console.log("no access");
        });
    });
}
if(preDefThemes) {
preDefThemes.addEventListener("click",(e) => {
    if(e.target!==e.currentTarget){
        theme= e.target.id;
        console.log(theme);
    }

    e.stopPropagation;
    });
}

if(micAccess) {
    micAccess.addEventListener("click", () => {
        navigator.webkitGetUserMedia({
            audio: true
        }, function (stream) {
            stream.stop();
        }, function () {
            console.log("no access");
        });
    });
}
```

**Other information:**
`Check from line number 30 in allowmic.js`

**System information:**

```
N/A
```

**Would you like to work on the issue?**
No.

**Comment by gabru-md** [comment]
@rupav you might want to check this issue in case you are interested to work on this.
this seems to be a relatively easy issue and can get you started on this project as well. :+1:
