### ISSUE TITLE
Erroneous code in extension

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#314]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Erroneous code.

**Expected behavior:**
Should not exhibit this error.

**Steps to reproduce:**
1.Clone fresh repo.
2.Load extension and check extension page.

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**
![screenshot_20180920_211502](https://user-images.githubusercontent.com/20766601/45830515-f0b51a00-bd1a-11e8-91ac-f4864eca63d4.png)

**System information:**
`Chrome V69`

```
Ubuntu 16.04
```

**Would you like to work on the issue?**
No.

**Comment by rupav** [comment]
Let me know @zamhaq if its still reproducible. What do you meant by extension page - console logs in the chrome://extensions?

**Comment by fragm3** [comment]
@zamhaq i'll take this up
