### ISSUE TITLE
Autofocus on textarea when extension pops up

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#32]
**Actual Behaviour**

When extension is clicked focus is not on the textarea

**Expected Behaviour**

When extension is clicked focus should be on the textarea

Yes I would like to work on it and make a relevant PR soon.

**Comment by ms10398** [comment]
@zamhaq @gabru-md 
Whats your opinion

**Comment by zamhaq** [comment]
go for it @ms10398

**Comment by gabru-md** [comment]
great @ms10398 :+1:
