### ISSUE TITLE
Add space between Logged in 'as,<user email>'

### ISSUE THREAD

**Issue by rupav** [fossasia/susi_chromebot#320]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

After logging in, if you try to log in again following message came
![loggedinbug](https://user-images.githubusercontent.com/20624380/45860865-27287e80-bd87-11e8-8479-5d325e58d6c1.png)

**Expected behavior:**

Instead it should be
![loggedin](https://user-images.githubusercontent.com/20624380/45860919-6bb41a00-bd87-11e8-9e99-41beeac4dcd1.png)

**Steps to reproduce:**

Log in, and then click on log in again.

**Would you like to work on the issue?**
Yes

**Comment by rupav** [comment]
@zamhaq can I send the fix for this in my already opened PR, #319 ?

**Comment by zamhaq** [comment]
> @zamhaq can I send the fix for this in my already opened PR, #319 ?

Yeah Sure :+1:

**Comment by rupav** [comment]
Done, also removed the Show Password field. Let me know if its fine.

**Comment by zamhaq** [comment]
Resolved through #319
