### ISSUE TITLE
Welcome/Introductory Message overlapping with previous messages if logged in.

### ISSUE THREAD

**Issue by rupav** [fossasia/susi_chromebot#323]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

If you log in, provided you had earlier chatted with SUSI in your account, then the message `Start by saying "HI"` overlaps the first message of your earlier chat.
Refer:
![hello_there](https://user-images.githubusercontent.com/20624380/45882587-3847ae80-bdcc-11e8-8113-fa391c34e04a.PNG)

**Expected behavior:**

If a person is logged in, and if there are previous messages, **dont show** welcome message - `Start by saying "Hi"`.

**Steps to reproduce:**
Log in on https://chat.susi.ai/ . Enter couple of queries. Then login with susi_chromebot, and scroll to top of the messages.

**Would you like to work on the issue?**
Yes

**Comment by rupav** [comment]
Well it checks if there is no access token before this message https://github.com/fossasia/susi_chromebot/blob/d9605641a28032d90fde332417e5fa82d84ad36c/src/script.js#L408 .
So shouldn't it not show this message @zamhaq  @gabru-md  If I am logged in?

**Comment by zamhaq** [comment]
@rupav True! It should not show this message if message history is present.

**Comment by rupav** [comment]
@zamhaq found the bug (wrong logic in the code), please see #324
