### ISSUE TITLE
Logout button on login screen

### ISSUE THREAD

**Issue by championballer** [fossasia/susi_chromebot#333]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
The logout button is present on the login page, which in my opinion should not be the case.

**Expected behavior:**
The logout button should be removed from this page and should be available only post login.

**Steps to reproduce:**
Open login.html in src folder of susi_chromebot

**Related Code**
```html
 <button class="btn btn-success" name="Logout" onClick="logout(this)" id="logout">Logout</button>
                        <br />
```

**Would you like to work on the issue?**
Yes

**Comment by gabru-md** [comment]
Assigned to you :)
