### ISSUE TITLE
Click to show password doesn't work as expected.

### ISSUE THREAD

**Issue by championballer** [fossasia/susi_chromebot#335]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
![show password](https://user-images.githubusercontent.com/39242078/45924645-fa10d300-bf22-11e8-9c78-8f43238bce7b.png)

The show password doesn't work on clicking on the checkbox.

**Expected behavior:**
The password being entered by user should be legible and not be hidden

**Steps to reproduce:**
Open login.html in src folder of susi_chromebot

**Would you like to work on the issue?**
Yes

**Comment by rupav** [comment]
Already a PR for the same. Refer #319

**Comment by championballer** [comment]
Yeah, my bad. Goodluck working on that. 

Also, could you comment here when it is merged? That will mean that there is no issue anymore?

**Comment by championballer** [comment]
@rupav Is the button you added working post the merge, for show password?

**Comment by rupav** [comment]
yes, I havent added the button, its a span tag (with an `eye` icon), clicking on which will let you see the password you typed.

**Comment by championballer** [comment]
It isn't working on my machine for some reason. Please check? 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39242078/45925490-15d0a500-bf34-11e8-8937-2f3ef785776d.gif)

**Comment by zamhaq** [comment]
@championballer Try to open this page from the extension instead opening the file directly. :smile:

**Comment by championballer** [comment]
Oh yeah, my bad. :smile:
