### ISSUE TITLE
Alignment of show password

### ISSUE THREAD

**Issue by championballer** [fossasia/susi_chromebot#336]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
The click to show password label and checkbox should be better aligned, that is they should be moved down to align properly on the page.

**Expected behavior:**
It should be lowered down a bit.

**Steps to reproduce:**
Open the login.html file in src of susi_chromebot

**Would you like to work on the issue?**
Yes

**Comment by rupav** [comment]
Already a PR for the same. Refer #319

**Comment by championballer** [comment]
I don't see any changes to the mentioned code in the PR, @rupav . It changes the redundant show password field but of the existing show password label which imo should be moved down a bit.
