### ISSUE TITLE
Redundant code in login.html

### ISSUE THREAD

**Issue by championballer** [fossasia/susi_chromebot#337]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
There is redundant code in login.html with display:none, where we already have show password label along with checkbox.
![reduncode](https://user-images.githubusercontent.com/39242078/45925020-f2552c80-bf2a-11e8-9ca9-fccace85c954.png)

![redun2](https://user-images.githubusercontent.com/39242078/45924829-46f6a880-bf27-11e8-8a60-9c4134dadee6.png)
![redunscreen](https://user-images.githubusercontent.com/39242078/45924830-49f19900-bf27-11e8-80a9-10e94ec3b4e5.png)
This is how it looks when we remove display:none from style attribue

**Expected behavior:**
This code is not required.

**Steps to reproduce:**
Open login.html in src folder of susi_chromebot

**Related code:**
![reduncode](https://user-images.githubusercontent.com/39242078/45925025-0305a280-bf2b-11e8-8464-3347c50a3c02.png)

**Would you like to work on the issue?**
Yes

**Comment by rupav** [comment]
Why would you remove `display:none` property? It is there in case user is logged in, then javascript will change that property itself.

**Comment by championballer** [comment]
I am so sorry, I by mistake attached wrong screenshot. I hope it clears your issue.

I don't really get the need of the whole block of code of "Show password" here when we already have a label and checkbox associated with it. Plus why on login screen do we need show password.
