### ISSUE TITLE
Open Chrome Extension to left as window

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_chromebot#344]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
Not present

**Expected behavior:**
Add option to open the chrome extension to left as a window

**Other information:**
See the redux dev tool for reference.
<img width="334" alt="screen shot 2018-09-23 at 1 50 50 pm" src="https://user-images.githubusercontent.com/18073126/45925687-d99f4380-bf37-11e8-9e98-08d8e520081f.png">

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Probably not needed for now.
