### ISSUE TITLE
Label Should be changed in confirm Password

### ISSUE THREAD

**Issue by Ananthavijay** [fossasia/susi_chromebot#353]
**I'm submitting a ...**  (check one with "x")
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**

![screenshot - 9_24_2018 12_31_09 am](https://user-images.githubusercontent.com/35162705/45931230-ce283880-bf88-11e8-8011-23a6da8d168a.png)

**Expected behavior:**

![screenshot - 9_24_2018 12_32_31 am](https://user-images.githubusercontent.com/35162705/45931234-d08a9280-bf88-11e8-8928-ef192ae59522.png)

**Steps to reproduce:**

Go to signup page .

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.

 Yes

**Comment by leoking-crey** [comment]
yes i would like to work on the issue please assign it to me

**Comment by leoking-crey** [comment]
Also please guide me through the steps required to do so as this would be my first pr

**Comment by leoking-crey** [comment]
I have placed a pull request please review
