### ISSUE TITLE
When eye is closed the password is shown and vice-versa 

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi_chromebot#389]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server

**Current behavior:**
When eye is closed the password is shown and vice-versa on the login page .
![pass chrome](https://user-images.githubusercontent.com/32234926/46270179-d02f6000-c563-11e8-89a4-6793735dba88.PNG)

**Expected behavior:**
When  eye is closed the password should be hidden and vice-versa
![pass1](https://user-images.githubusercontent.com/32234926/46270204-f94ff080-c563-11e8-871e-eb1c51634ce1.PNG)

**Would you like to work on the issue?**
Yes

**Comment by rupav** [comment]
Not able to produce this issue.

**Comment by rupav** [comment]
Yes, my bad. Go ahead. Send a PR. Thanks for spotting it. It was my mistake when I sent the PR for this. Please rectify it.
