### ISSUE TITLE
Add Share functionality in Message Response

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_chromebot#395]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our [Gitter channel](https://gitter.im/fossasia/susi_server)

**Current behavior:**
Not sharing facility present at the moment

**Expected behavior:**
Add sharing the message in message response.
<img width="498" alt="screenshot 2018-10-02 at 1 25 12 pm" src="https://user-images.githubusercontent.com/18073126/46335883-9e42fa00-c646-11e8-96ee-6e47d77138af.png">

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

```
Your operating system
```

**Would you like to work on the issue?**
Yes

**Comment by rupav** [comment]
Are you working on it @fragm3 . I would like to claim it if not.

**Comment by fragm3** [comment]
@rupav I am working on it
