### ISSUE TITLE
Fix Cannot read property 'addEventListener' of null in restore

### ISSUE THREAD

**Issue by fragm3** [fossasia/susi_chromebot#407]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our [Gitter channel](https://gitter.im/fossasia/susi_server)

**Current behavior:**
SC:
<img width="621" alt="screenshot 2018-10-04 at 9 57 51 pm" src="https://user-images.githubusercontent.com/18073126/46488575-ac4c7280-c820-11e8-9b57-89de6e567639.png">

`Uncaught TypeError: Cannot read property 'addEventListener' of null
    at options.js:106`

**Expected behavior:**
Fix it

**Steps to reproduce:**
Open console to see the error

**Would you like to work on the issue?**

Yes

**Comment by tathagat2006** [comment]
I want to resolve #407

**Comment by fragm3** [comment]
Already working on it.
