### ISSUE TITLE
Addings Settings Link Inside Drop Down Menu

### ISSUE THREAD

**Issue by sk9331657** [fossasia/susi_chromebot#417]
**I'm submitting a ...**  (check one with "x")
- [x] feature request

**Current behavior:**

There is no link to Settings.html in the drop-down menu in chrome bot.

![screenshot from 2018-10-05 16-05-27](https://user-images.githubusercontent.com/17084322/46530816-9c806d00-c8b8-11e8-86f0-b04ee0391389.png)

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.
```
Yes

**Comment by tathagat2006** [comment]
Yes

**Comment by sk9331657** [comment]
> I want to resolve #417

Already solved in #418.  :smile:  Try another issue.
