### ISSUE TITLE
susi chats lost after reopening the extension

### ISSUE THREAD

**Issue by rajvaibhavdubey** [fossasia/susi_chromebot#446]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our [Gitter channel](https://gitter.im/fossasia/susi_server)

**Current behavior:**

The replies by susi disappear while the user text remains. 

**System information:**

```
Your operating system
Linux
```

**Would you like to work on the issue?**
Yes

**Comment by samagragupta** [comment]
Can I work on it?

**Comment by rajvaibhavdubey** [comment]
I'm working on this. :smile:

**Comment by samagragupta** [comment]
If you are not able to do it, then inform me as I have done the work 😄
