### ISSUE TITLE
Add padding 

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi_chromebot#468]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our [Gitter channel](https://gitter.im/fossasia/susi_server)

**Current behavior:**
There is no space between the change password form and screen.
![chrome](https://user-images.githubusercontent.com/32234926/48177407-64969a80-e33a-11e8-8ace-a4f86224b8cc.PNG)

**Expected behavior:**
Add some space between the change password form and screen.
 
```
Your operating system: WIndows
```

**Would you like to work on the issue?**

Yes

**Comment by neeraj3029** [comment]
@samagragupta In my system it looks fine.

![screenshot 2018-11-08 at 12 05 05 pm](https://user-images.githubusercontent.com/31539812/48181759-ca8d1d00-e34e-11e8-8ecf-3bdced34a55a.png)

**Comment by sk9331657** [comment]
@samagragupta  Space is already present.
