### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#49]
Input box can be adjusted to fill the white space available.
@zamhaq @gabru-md 
Whats your opinion

Screenshot of the issue

![screenshot from 2017-09-25 03-18-18](https://user-images.githubusercontent.com/26259547/30787248-013585da-a1a2-11e7-8268-612c0d5170e5.png)

Yes I would like to work on the issue if this change is required

**Comment by gabru-md** [comment]
@ms10398 good! 
I was thinking of creating an issue about it as well.
Thanks for doing so. :+1:

**Comment by ms10398** [comment]
I will make a relevant PR soon
