### ISSUE TITLE
Reduce the size of text(time)

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi_chromebot#491]
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our [Gitter channel](https://gitter.im/fossasia/susi_server)

**Current behavior:**
The time get out of the message component.
![text](https://user-images.githubusercontent.com/32234926/48978566-0f48e000-f0d3-11e8-81fa-d0bf20db7e17.PNG)

**Expected behavior:**
The size time text should be reduced so that it can fit in the container.

```
Your operating system: Windows
```

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.
Yes

**Comment by zamhaq** [comment]
@samagragupta Still working on this?

**Comment by samagragupta** [comment]
> @samagragupta Still working on this?

Yes
