### ISSUE TITLE
Add Option to login on Settings Page 

### ISSUE THREAD

**Issue by sk9331657** [fossasia/susi_chromebot#505]
[x] Feature request 
**Actual Behaviour**
There is no link to help the user to log in.

**Expected Behaviour**
There should be link to login.

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes
![screenshot from 2018-12-15 21-14-30](https://user-images.githubusercontent.com/17084322/50041798-8cd39080-0080-11e9-932a-bb62a79756cf.png)

**Comment by adityavats007** [comment]
How to take up this issue? I would like to take this up.
