### ISSUE TITLE
Toggle Eye Not working properly 

### ISSUE THREAD

**Issue by sk9331657** [fossasia/susi_chromebot#514]
**I'm submitting a ...**  
- [x] bug report

**Current behavior:**

When login page open , eye is open but it should be closed as input is password and thus when i toggle it , eye is closed but password in text form.

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

**Screenshots of the issue:**

```
Your operating system
```

**Would you like to work on the issue?**

```
Yes.

**Comment by shreyansh-goyal** [comment]
I want to handle this issue.
When I opened the login page the eye was opened but the password was hidden and clicking on eye is not causing any effect.

**Comment by shreyansh-goyal** [comment]
I thought you raised this issue.I carefully watched that bug the document.addEventListener is not working.I even tried console.log but even that didn't work.

**Comment by sk9331657** [comment]
@shreyansh-goyal  It is just element class issues. It is now resolved.
