### ISSUE TITLE
Color Picker not defined in popup.html

### ISSUE THREAD

**Issue by sk9331657** [fossasia/susi_chromebot#515]
**I'm submitting a ...**  
- [x] bug report

**Current behavior:**

As color-picker tag is present only in options.html , thus when I open popup.html, them color picker throws undefined error . 
**Expected behavior:**

Using try catch to find if color picker is present of not.

**Steps to reproduce:**

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:**

**Screenshots of the issue:**

```
Your operating system
```

**Would you like to work on the issue?**

```
Yes.

![screenshot from 2018-12-28 02-17-15](https://user-images.githubusercontent.com/17084322/50493994-bf996380-0a46-11e9-9659-0783acbbf810.png)

**Comment by Puranjay25** [comment]
Could you please elaborate your issue, because on my screen everything is working fine.

**Comment by sk9331657** [comment]
Just open the extension console to see error.
