### ISSUE TITLE
Leading spaces

### ISSUE THREAD

**Issue by rupav** [fossasia/susi_chromebot#52]
Leading space in chat :
![2017-09-25 5](https://user-images.githubusercontent.com/20624380/30810768-c402396a-a223-11e7-98c5-72047936681f.png)

**How to reproduce it?**
Follow the steps in readme to make SUSI work, then start chatting.

I would like to work on it, if thats an issue. 
A little guide where to look for will be really helpful?
Thanks.
I am new to Javascript.

**Comment by stealthanthrax** [comment]
@rupav could you please elaborate on this issue

**Comment by gabru-md** [comment]
@rupav thanks for notifying us.
But this issue is already known and is been worked upon by @ms10398 .
He has been working on UI enhancement and should soon be sending a PR

Thanks again. :)

**Comment by ms10398** [comment]
@rupav Yes that issue is already resolved you can work on any other issue or any other feature you want to add to the community

**Comment by gabru-md** [comment]
This issue can now be closed.

**Comment by rupav** [comment]
ok @gabru-md  @ms10398. Thanks.
