### ISSUE TITLE
No option for voice input

### ISSUE THREAD

**Issue by samagragupta** [fossasia/susi_chromebot#544]
**I'm submitting a ...**  
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in our [Gitter channel](https://gitter.im/fossasia/susi_server)

**Current behavior:**
When a message is sent. After that, there is no option for voice input.

**Expected behavior:**
When a message is sent. After that also there should be an option for voice input.

**Would you like to work on the issue?**
Yes

**Comment by mariobehling** [comment]
Low priority
