### ISSUE TITLE
Integrate google webspeech api

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#56]
Integrate google webspeech api for :- 
- [ ] Text To Speech
- [ ] Speech input

Yes, I would work on this.

**Comment by gabru-md** [comment]
Will work on this.

**Comment by zamhaq** [comment]
@gabru-md Sorry I forgot to write it before, I am working on it :smile:

**Comment by gabru-md** [comment]
Okay! No problem 
You can always take my help when you need 
:+1:

**Comment by zamhaq** [comment]
@gabru-md cool.
