### ISSUE TITLE
Add .eslintrc file

### ISSUE THREAD

**Issue by S2606** [fossasia/susi_chromebot#60]
For javascript linting purposes.

**Would you like to work in this issue?**
Yes

**Comment by zamhaq** [comment]
@S2606 `eslint` is not being used. Project uses `jshint`

**Comment by zamhaq** [comment]
@gabru-md @ms10398 Are you guys using `.jshintrc` to integrate `jshint` with your `editor` ? I am making my `PR` soon, so if you guys are using `.jshintrc` then I will be committing it, otherwise I will ignore it. Please confirm.

**Comment by ms10398** [comment]
We are using gruntfile which has jshint configurations @zamhaq

**Comment by zamhaq** [comment]
so you run the `grunt task`. But I am using `.jshintrc` integration with my `vscode`. So, is it a problem if I upload the file or should I just ignore it ?

**Comment by ms10398** [comment]
Yes we are running grunt task. We will not need `.jshintrc` because we have all configurations in gruntfile so maybe no need to commit it.

**Comment by zamhaq** [comment]
@ms10398 ok cool.
