### ISSUE TITLE
Theme Preferences

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#63]
**Feature Request**

There should be light and dark theme supported as [Susi Chat](http://chat.susi.ai).

**Would you like to work on it?**

Yes I would like to work on it.

**Comment by gabru-md** [comment]
@ms10398 if you're not working then can i please ?

**Comment by ms10398** [comment]
@gabru-md I am working on it its almost done

**Comment by gabru-md** [comment]
:+1:
