### ISSUE TITLE
Disable the mic input until the first event completely ends.

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#65]
Actual Behaviour :- 
The mic input can be pressed several times which will lead to multiple events being registered.

Expected Behaviour :- 
Disable the mic input until the first speech recognition event completely ends.

**Comment by gabru-md** [comment]
@zamhaq i would like to try working on it.

**Comment by zamhaq** [comment]
@gabru-md Sure. :+1:

**Comment by harshit98** [comment]
What's the status of this issue @zamhaq @gabru-md ?

**Comment by zamhaq** [comment]
@harshit98 @gabru-md should be working on this as he claimed the issue. @gabru-md are you working on it?

**Comment by gabru-md** [comment]
@zamhaq I'm currently very ill and undergoing treatment. So i may not be able to work for some time. You can give this issue to someone else.
Sorry

**Comment by zamhaq** [comment]
@gabru-md Oh, No problem. I'll open your issues for someone else.

**Comment by zamhaq** [comment]
@gabru-md I think this is not required. The mic works as on/off switch for speech recognition. If we disable the `mic` after the user clicks it once, he would not be able to click the mic to turn off the recognition and would have to wait for recognition to end automatically.
