### ISSUE TITLE
Fixing UI issues

### ISSUE THREAD

**Issue by S2606** [fossasia/susi_chromebot#69]
![image](https://user-images.githubusercontent.com/18497513/30899059-ec4a657e-a37b-11e7-8278-e6ffc6051fd7.png)
As we can see some fixing needs to be taken care of.

**Would you like to work on this one?**
Yes

**Comment by gabru-md** [comment]
@S2606 please describe the changes you propose

**Comment by S2606** [comment]
@gabru-md 

- Fixing the settings icon location

- Using space of input text and submit button

**Comment by gabru-md** [comment]
There is a seperate issue for settings icon which I'm working upon. 
I guess the spacing was fixed before ? Am i right @zamhaq

**Comment by ms10398** [comment]
Yes one issue is fixed and on one issue @gabru-md is already working @S2606

**Comment by zamhaq** [comment]
Close this issue ?
