### ISSUE TITLE
Theme Change error

### ISSUE THREAD

**Issue by gabru-md** [fossasia/susi_chromebot#75]
**Expected Behaviour**
Changing the theme causes the previous messages to remain in same way.

**Actual Behaviour**
It must be changed and should adapt to the changed theme.

**Yes** I will work on this.

**Comment by gabru-md** [comment]
@zamhaq Will start working on it tomorrow.
:+1:

**Comment by ms10398** [comment]
@gabru-md May I work on it

**Comment by gabru-md** [comment]
Okay! Because you implemented the theme changes. It would be easier for you to do the changes.
Thanks !
Cheers

**Comment by ms10398** [comment]
Yes Sure Will work on it Thanks ! Welcome

**Comment by ms10398** [comment]
Sorry for delay in the PR as my college exams were going on. I will make the PR tomorrow after completing it today.
