### ISSUE TITLE
There is an issue when I ask susi to get me a meme 

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#77]
![issue](https://user-images.githubusercontent.com/29942790/30929108-1782cd9e-a3db-11e7-9dc5-594aa98d40d9.png)

**Comment by stealthanthrax** [comment]
it displays the the file path also

**Comment by ms10398** [comment]
This is a server issue and the changes are happening in the server
So we cant change anything on the extension side

**Comment by gabru-md** [comment]
Thanks for letting us know!
We will take care of it. 
I will work on it as well @zamhaq .

**Comment by ms10398** [comment]
@gabru-md We cant do anything try this query on susi chat you will get to know

**Comment by zamhaq** [comment]
yes @ms10398 is correct. @stealthanthrax Thanks for reporting but thats a problem on the backend. You could report the same issue on that repo if it is not already present.

**Comment by gabru-md** [comment]
cool ! thanks for letting me know

**Comment by stealthanthrax** [comment]
ok thanks @zamhaq @ms10398 @gabru-md
