### ISSUE TITLE
Add .jshintrc file for automatic detection on codacy 

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#78]
With the .jshintrc file provided, I won't have to manually configure it.

I will be adding `.jshintrc` if thats fine with you guys @ms10398 @gabru-md ?

**Comment by ms10398** [comment]
@zamhaq Yes sure go ahead configuring codacy is a important thing.

**Comment by gabru-md** [comment]
@zamhaq go on with it ! It is good to have codacy involved to keep a check of code quality.
