### ISSUE TITLE
Can we replace the settings icon menu with a drop down or side menu

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_chromebot#82]
The main purpose of making the susi chrome bot was that the user doesn't have to leave his work to use SUSI .But having to open a seperate page really destroys the purpose.

**If yes**
 I would like work on this issue

**Comment by stealthanthrax** [comment]
@gabru-md @zamhaq @ms10398

**Comment by zamhaq** [comment]
Don't know about that. You could definitely open an **iframe** or a new **window**. The **Tab** solution is definitely a bad user experience.

**Comment by stealthanthrax** [comment]
So,should I start working on this issue?

**Comment by zamhaq** [comment]
Sure. Go for it.

**Comment by stealthanthrax** [comment]
Thansk @zamhaq

**Comment by zamhaq** [comment]
@stealthanthrax while you work on this, if you go for an **iframe** or a **window**, open the **options.html** file inside it. :+1:

**Comment by stealthanthrax** [comment]
@zamhaq could you please explain me more about options.html?

**Comment by zamhaq** [comment]
Please search for chrome extensions and microphone access issue. The new tab that opens is there so that extension can have microphone access. If you want to replace the tab, then it must be a window or an iframe.

**Comment by harshit98** [comment]
What's the status of this issue? @stealthanthrax

**Comment by stealthanthrax** [comment]
@zamhaq i will be using js in this issue ,if not a problem

**Comment by stealthanthrax** [comment]
@harshit98 i have been facing some problems in my other pr on this project , i am trying to figure them out first
