### ISSUE TITLE
Replace the gif in readme with the lastest gif

### ISSUE THREAD

**Issue by ms10398** [fossasia/susi_chromebot#89]
The Gif in the readme is of the old extension so it should be replaced with the latest extension

Yes I would like to work on it and make a relevant PR soon.

**Comment by gabru-md** [comment]
@ms10398 I guess that this issue can wait. since there are a lot of changes being made to susi_chromebot.
Therefore when we are done quite a lot with it, then you can do it.

**Comment by ms10398** [comment]
Yes I have put this issue on hold as lots of changes are being made :+1:

**Comment by ms10398** [comment]
This issue is on hold after some time we will open it as the extension is changing a lot on daily basis.

**Comment by VRamazing** [comment]
@ms10398  ok

**Comment by stealthanthrax** [comment]
@ms10398 , i think we should assign it as a GCI task?

**Comment by gabru-md** [comment]
It has been done @stealthanthrax

**Comment by 0x48piraj** [comment]
I'm on it! :heart:

**Comment by 0x48piraj** [comment]
@gabru-md Can I know the task `url` ?
I'm having difficulty finding that one.
