### ISSUE TITLE
Add different icon sizes in manifest.json

### ISSUE THREAD

**Issue by rupav** [fossasia/susi_chromebot#92]
This is to ensure susi.ai icon'size on the toolbar is compatible with the platform used.
I had done similar type in fossasia/susi_firefoxbot [https://github.com/fossasia/susi_firefoxbot/pull/22](url) where I used an svg icon.
But Chrome does not show svg icon so will do something else.
Also, recommended sizes are:
[https://developer.chrome.com/apps/manifest/icons](url) .

**Would you like to work on it?**
Yes.

**Comment by rupav** [comment]
@gabru-md  @zamhaq is this needed to be done?

**Comment by gabru-md** [comment]
As i spoke to you 
This is not required.
But you can still add a 48X48 icon if you want.
@zamhaq close this issue please. Please make a PR if you want to add the 48X48 icon
Thanks!
