### ISSUE TITLE
Make chat data persistent

### ISSUE THREAD

**Issue by zamhaq** [fossasia/susi_chromebot#97]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/susi_server
 
 **Current behavior:**
 Once the browser action is closed all chat data is lost.
 
 **Expected behavior:**
 Chat data should be preserved unless user closes it.

**Yes. I would work on this.**

**Comment by ms10398** [comment]
Yes we could implement this feature after you implement this feature I would like to add the Clear all button.

**Comment by ms10398** [comment]
Whats the status @zamhaq

**Comment by zamhaq** [comment]
Been busy working on several issues. Will work on this from now. Sorry for delaying. :smile:

**Comment by ms10398** [comment]
No issues :+1: If need any help feel free to contact will always love to contribute :smile:
