### ISSUE TITLE
Mic is not working

### ISSUE THREAD

**Issue by rupav** [fossasia/susi_chromebot#99]
On clicking mic, there is no response, "SPEAK NOW" comes on top and vanishes quickly.
It is not registering our chat using mic.
![2017-10-01 3](https://user-images.githubusercontent.com/20624380/31054521-d178c28c-a6d1-11e7-94da-d92d96959313.png)
**Would you like to work on it?**
Yes.

**Comment by zamhaq** [comment]
@rupav did you enable mic?

**Comment by rupav** [comment]
@zamhaq  Sorry, I just did and its working fine. Sorry, my bad. Can you please update the readme :)

**Comment by zamhaq** [comment]
@rupav you can do that or you can create a new issue `alerting the user if the mic is not allowed`. :smile: You can work on it if you want to.
